RastreioConnectParts/Controllers/RastreioController.cs
using Atlassian.Jira.Remote;
using Newtonsoft.Json;
using RastreioConnectParts.Context;
using RastreioConnectParts.CorreiosRastro;
using RastreioConnectParts.Models;
using RastreioConnectParts.Models.Correios;
using RastreioConnectParts.Models.Intelipost;
using RastreioConnectParts.Models.Loggi;
using RastreioConnectParts.Models.NowLog;
using RastreioConnectParts.Models.Rodonaves;
using RastreioConnectParts.Models.Transfolha;
using RestSharp;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using System.Xml.Linq;

namespace RastreioConnectParts.Controllers
{
    public class RastreioController : Controller
    {
        private PainelDeMonitoracaoContext db = new PainelDeMonitoracaoContext();

        [HttpGet]
        public ActionResult Index(string c)
        {
            var transportadoras = db.RastreioTransportadoras.ToList();

            if (!String.IsNullOrEmpty(c))
            {
                PedidoRastreio pedido = RecuperaPedido(c);

                if (pedido == null)
                {
                    string msg = "Não foi possível localizar seu pedido.";
                    ViewData["msg"] = msg;
                    return View("Error");
                }

                string cnpj = CnpjRastreio(pedido.PedidoUnidadeNegocio);

                Rastreio rastreio = new Rastreio();

                #region Gol Log
                if (pedido.PedidoTransportadoraCodigo == 5 && transportadoras.Where(t => t.Nome == "Gol Log").FirstOrDefault().RastreioIntelipost == false)
                {
                    return Redirect($"https://edi.voegol.com.br/ediportal/rastreamento/padrao.aspx?cnpj={cnpj}&modo=0&notafiscal={pedido.NotaFiscalNumero}");
                }
                #endregion

                #region TNT
                if (pedido.PedidoTransportadoraCodigo == 4 && transportadoras.Where(t => t.Nome == "TNT").FirstOrDefault().RastreioIntelipost == false)
                {
                    return Redirect($"https://radar.tntbrasil.com.br/radar/public/eventoNotaFiscalCliente/{cnpj}/{pedido.NotaFiscalNumero}-{pedido.NotaFiscalSerie}");
                }
                #endregion

                try
                {
                    rastreio = Rastrear(pedido);
                }
                catch (Exception e)
                {
                    string msg = "Seu pedido está em processamento de transporte.";
                    ViewData["msg"] = msg;
                    return View("Error");
                }

                ViewBag.Movimentacao = rastreio.Movimentos;
                ViewBag.DataEstimada = rastreio.DataEstimada;
                ViewBag.Metodo = rastreio.Metodo;
                ViewBag.Transportadora = rastreio.Transportadora;
                ViewBag.Status = rastreio.Status;

                return View();
            }

            return RedirectToAction("Pesquisar");

        }

        [HttpPost]
        public ActionResult Pesquisar(string codigo)
        {
            return RedirectToAction("Index", new { c = codigo });
        }

        [HttpGet]
        public ActionResult Pesquisar()
        {

            return View();
        }

        /// <summary>
        /// Recupera o obj de pedido simplificado do Ábacos baseando-se apenas no número de rastreio do mesmo
        /// </summary>
        /// <param name="numeroRastreio">Número de rastreio</param>
        /// <returns>Objeto de pedido simplifacado</returns>
        public PedidoRastreio RecuperaPedido(string numeroRastreio)
        {
            RestClient client = new RestClient("http://api.dakotaparts.com.br/Fenix");
            string recurso = $"/Frete/BuscarSimples/?&numeroRastreio={numeroRastreio}";

            var requisicao = new RestRequest(recurso, Method.GET)
            {
                RequestFormat = DataFormat.Json,
                JsonSerializer = new RestSharpJsonSerializer()
            };

            requisicao.AddHeader("Accept", "application/json");
            requisicao.AddHeader("Content-Type", "application/json");

            IRestResponse resposta = client.Execute(requisicao);

            PedidoRastreio pedido_rastreio = JsonConvert.DeserializeObject<PedidoRastreio>(resposta.Content);

            return pedido_rastreio;
        }

        /// <summary>
        /// Define qual o CNPJ (unidade fiscal ou matriz) a ser utilizado para rastreio
        /// </summary>
        /// <param name="unidadeNegocio">Unidade de negócio do pedido</param>
        /// <returns>CPNJ de rastreio</returns>
        public string CnpjRastreio(int unidadeNegocio)
        {
            if (unidadeNegocio == 1)
            {
                return "08677036000116";
            }
            else if (unidadeNegocio == 5)
            {
                return "08677036000388";
            }
            return "";
        }

        /// <summary>
        /// Rastreia o pedido de acordo com o parametro de rastreio ativo no Painel do TI, podendo ser via transportadora ou INtelipost
        /// </summary>
        /// <param name="pedido">Objeto de pedido simplificado</param>
        /// <returns>Lista de movimentação dos pacotes</returns>
        public Rastreio Rastrear(PedidoRastreio pedido)
        {
            string cnpj = CnpjRastreio(pedido.PedidoUnidadeNegocio);
            List<Movimento> eventos = new List<Movimento>();
            Rastreio rastreio = new Rastreio();

            var transportadoras = db.RastreioTransportadoras.ToList();

            #region Loggi
            if (pedido.PedidoTransportadoraCodigo == 53)
            {
                if (transportadoras.Where(t => t.Nome == "Loggi").FirstOrDefault().RastreioIntelipost == false)
                {
                    rastreio.Movimentos = GerarEventosViaLoggi(pedido);
                }
                else
                {
                    rastreio = GerarEventosViaIntelipost(pedido);
                }

            }
            #endregion

            #region NowLog
            if (pedido.PedidoTransportadoraCodigo == 45)
            {
                if (transportadoras.Where(t => t.Nome == "NowLog").FirstOrDefault().RastreioIntelipost == false)
                {
                    rastreio.Movimentos = GerarEventosViaNowLog(pedido, cnpj);
                }
                else
                {
                    rastreio = GerarEventosViaIntelipost(pedido);
                }

            }
            #endregion

            #region Rodonaves
            if (pedido.PedidoTransportadoraCodigo == 8)
            {
                if (transportadoras.Where(t => t.Nome == "Rodonaves").FirstOrDefault().RastreioIntelipost == false)
                {
                    rastreio.Movimentos = GerarEventosViaRodonaves(pedido, cnpj);
                }
                else
                {
                    rastreio = GerarEventosViaIntelipost(pedido);
                }
            }
            #endregion

            #region Transfolha
            if (pedido.PedidoTransportadoraCodigo == 44)
            {
                if (transportadoras.Where(t => t.Nome == "Transfolha").FirstOrDefault().RastreioIntelipost == false)
                {
                    rastreio.Movimentos = GerarEventosViaTransfolha(pedido);
                }
                else
                {
                    rastreio = GerarEventosViaIntelipost(pedido);
                }
            }
            #endregion

            #region Correios
            if (pedido.PedidoTransportadoraCodigo == 1 || pedido.PedidoTransportadoraCodigo == 58 || pedido.PedidoTransportadoraCodigo == 61)
            {
                if (transportadoras.Where(t => t.Nome == "Correios").FirstOrDefault().RastreioIntelipost == false)
                {
                    rastreio.Movimentos = GerarEventosViaCorreios(pedido);
                }
                else
                {
                    rastreio = GerarEventosViaIntelipost(pedido);
                }
            }
            #endregion

            #region Gol Log
            if (pedido.PedidoTransportadoraCodigo == 5 && transportadoras.Where(t => t.Nome == "Gol Log").FirstOrDefault().RastreioIntelipost == true)
            {
                rastreio = GerarEventosViaIntelipost(pedido);
            }
            #endregion

            #region TNT
            if (pedido.PedidoTransportadoraCodigo == 4 && transportadoras.Where(t => t.Nome == "TNT").FirstOrDefault().RastreioIntelipost == true)
            {
                rastreio = GerarEventosViaIntelipost(pedido);
            }
            #endregion

            return rastreio;
        }

        /// <summary>
        /// Gera a listagem de eventos de rastreio Intelipost com tratamento direcionado para transpotadora no caso de ocorrência de erro
        /// </summary>
        /// <param name="pedido">Objeto pedido</param>
        /// <returns>Lista de enventos do objeto rastreado</returns>
        public Rastreio GerarEventosViaIntelipost(PedidoRastreio pedido)
        {
            List<Movimento> eventos = new List<Movimento>();
            Rastreio rastreio = new Rastreio();

            IntelipostRastreio rastreioIntelipost = RastrearIntelipost(pedido.NumeroRastreio);

            try
            {
                rastreio.DataEstimada = rastreioIntelipost.content[0].estimated_delivery_date_iso;
                rastreio.Transportadora = rastreioIntelipost.content[0].logistic_provider_name;
                rastreio.Metodo = rastreioIntelipost.content[0].delivery_method_name;
                rastreio.Status = rastreioIntelipost.content[0].shipment_order_volume_array[0].shipment_order_volume_state_localized;

                if (rastreioIntelipost.content[0].shipment_order_volume_array[0].shipment_order_volume_state_history_array.Any())
                {

RastreioConnectParts/Views/Rastreio/Index.cshtml
@{
    ViewBag.Title = "Rastreio de encomenda";
}

<br />
<br />
<br />
<br />

@{
    if (String.IsNullOrEmpty(ViewBag.Erro))
    {
        if (!String.IsNullOrEmpty(ViewBag.Transportadora))
        {

            <div class="progress-tracking">
                <div class="circle">
                    <span class="label"><i class="fas fa-check"></i></span>
                    <span class="title">Criado</span>
                </div>
                <span class="bar"></span>
                <div class="circle">
                    <span class="label"><i class="far fa-paper-plane"></i></span>
                    <span class="title">Despachado</span>
                </div>
                <span class="bar"></span>
                <div class="circle">
                    <span class="label"><i class="fas fa-hourglass-half"></i></span>
                    <span class="title">Em trânsito</span>
                </div>
                <span class="bar"></span>
                <div class="circle">
                    <span class="label"><i class="fas fa-shuttle-van"></i></span>
                    <span class="title">Saiu para entrega</span>
                </div>
                <span class="bar"></span>
                <div class="circle">
                    <span class="label"><i class="fas fa-home"></i></span>
                    <span class="title">Entregue</span>
                </div>
            </div>

            <br />
        }

        <div class="row">
            <table class="table">
                <thead>
                    <tr align="center" class="warning">
                        <th width="25%">Data/Hora</th>
                        <th width="25%">Evento</th>
                        <th width="25%">Detalhes</th>
                        <th width="25%">Observação</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var movimento in ViewBag.Movimentacao)
                    {
                    <tr>
                        <td>@movimento.Data</td>
                        <td style="text-align: left">@movimento.Evento</td>
                        <td style="text-align: left">@movimento.Detalhes</td>
                        <td style=" text-align: left ">@movimento.Observacao</td>
                    </tr>
                    }
                </tbody>
            </table>
        </div>
    }
    else
    {
        <div class="col-lg-12">
            <div class="bs-component">
                <div class="alert alert-dismissible alert-danger">
                    <strong>Número de rastreio não encontrado</strong>
                </div>
            </div>
        </div>
    }

}

@section Scripts {
    <script type="text/javascript">
        var i = 1;
        var status = "@Convert.ToString(ViewBag.Status)";

        if (status == "Criado") {
            limite = 1;
        }
        if (status == "Despachado") {
            limite = 2;
        }
        if (status == "Em trânsito" || status == "Em tr&#226;nsito") {
            limite = 3;
        }
        if (status == "Saiu para entrega") {
            limite = 4;
        }
        if (status == "Falha na entrega" || status =="Averiguar falha na entrega") {
            limite = 4;
        }
        if (status == "Entregue") {
            limite = 6;
        }

        $('.progress-tracking .circle').removeClass().addClass('circle');
        $('.progress-tracking .bar').removeClass().addClass('bar');


        if (i == 0) {
            $('.progress-tracking .bar').removeClass().addClass('bar');
            $('.progress-tracking div.circle').removeClass().addClass('circle');
            i = 1;
        }

        do {           

            if ((status == "Falha na entrega" || status =="Averiguar falha na entrega") && i == 4) {
                $('.progress-tracking .circle:nth-of-type(' + i + ')').addClass('problem');
                $('.progress-tracking .circle:nth-of-type(' + (i) + ') .label').html('<i class="fas fa-times"></i>');
            }
            else {
                $('.progress-tracking .circle:nth-of-type(' + i + ')').addClass('active');
            }

            $('.progress-tracking .circle:nth-of-type(' + (i - 1) + ')').removeClass('active').addClass('done');

            $('.progress-tracking .circle:nth-of-type(' + (i - 1) + ') .label').html('<i class="fas fa-check"></i>');

            $('.progress-tracking .bar:nth-of-type(' + (i - 1) + ')').addClass('active');

            $('.progress-tracking .bar:nth-of-type(' + (i - 2) + ')').removeClass('active').addClass('done');
            i++;
        } while (i <= limite);


    </script>
}

RastreioConnectParts/Views/Rastreio/Pesquisar.cshtml
@{
    ViewBag.Title = "Pesquisar Rastreio";
}
<br />
<br />
<br />
<br />
<br />
<div>
    <form method="POST" action="@Url.Action("Pesquisar", "Rastreio")">
        <div class="form-group">
            <div class="input-group">
                <input type="text" name="codigo" class="form-control" placeholder="Digite o código de rastreio da transportadora...">
                <span class="input-group-btn">
                    <button class="btn btn-default" type="submit">Pesquisar</button>
                </span>
            </div>
        </div>
    </form>
</div>